[build]
  publish = "dist/spa"
  command = "quasar build"

[context.production.environment]
  APP_NAME = "Teloscan"
  NODE_VERSION = "14"
  NETWORK_CHAIN_ID = "4667b205c6838ef70ff7988f6e8257e8be0e1284a2f59699054a018f743b1d11"
  NETWORK_HOST = "telos.caleos.io"
  NETWORK_PORT = "443"
  NETWORK_PROTOCOL = "https"
  NETWORK_EVM_RPC = "https://mainnet.telos.net/evm"
  NETWORK_EVM_ENDPOINT = "https://mainnet.telos.net"
  NETWORK_EVM_CONTRACT = "eosio.evm"
  NETWORK_EVM_CHAIN_ID = "40"
  NETWORK_EXPLORER = "https://explorer.telos.net"
  HYPERION_ENDPOINT = "https://mainnet.telos.net"
  TELOS_API_ENDPOINT = "https://api.telos.net"
  VERIFIED_CONTRACTS_BUCKET = "verified-evm-contracts"

  STLOS_CONTRACT_ADDRESS = ""
  STLOS_ESCROW_CONTRACT_ADDRESS = ""

[context.dev.environment]
  APP_NAME = "Teloscan Testnet"
  NODE_VERSION = "14"
  NETWORK_CHAIN_ID = "1eaa0824707c8c16bd25145493bf062aecddfeb56c736f6ba6397f3195f33c9f"
  NETWORK_HOST = "testnet.telos.net"
  NETWORK_PORT = "443"
  NETWORK_PROTOCOL = "https"
  NETWORK_EVM_RPC = "https://testnet.telos.net/evm"
  NETWORK_EVM_ENDPOINT = "https://testnet.telos.net"
  NETWORK_EVM_CONTRACT = "eosio.evm"
  NETWORK_EVM_CHAIN_ID = "41"
  NETWORK_EXPLORER = "https://explorer-test.telos.net"
  HYPERION_ENDPOINT = "https://testnet.telos.net"
  TELOS_API_ENDPOINT = "https://api-dev.telos.net"
  VERIFIED_CONTRACTS_BUCKET = "verified-evm-contracts-testnet"

  STLOS_CONTRACT_ADDRESS = "0xcF567fD3B5D05934a769b108DaA1c931dd529793"
  STLOS_ESCROW_CONTRACT_ADDRESS = "0xB679ab23726d7EaF1b3b807b018A27362E7B85F8"

[context.deploy-preview.environment]
  APP_NAME = "Teloscan Testnet"
  NODE_VERSION = "14"
  NETWORK_CHAIN_ID = "1eaa0824707c8c16bd25145493bf062aecddfeb56c736f6ba6397f3195f33c9f"
  NETWORK_HOST = "testnet.telos.net"
  NETWORK_PORT = "443"
  NETWORK_PROTOCOL = "https"
  NETWORK_EVM_RPC = "https://testnet.telos.net/evm"
  NETWORK_EVM_ENDPOINT = "https://testnet.telos.net"
  NETWORK_EVM_CONTRACT = "eosio.evm"
  NETWORK_EVM_CHAIN_ID = "41"
  NETWORK_EXPLORER = "https://explorer-test.telos.net"
  HYPERION_ENDPOINT = "https://testnet.telos.net"
  TELOS_API_ENDPOINT = "https://api-dev.telos.net"
  VERIFIED_CONTRACTS_BUCKET = "verified-evm-contracts-testnet"

  STLOS_CONTRACT_ADDRESS = "0xcF567fD3B5D05934a769b108DaA1c931dd529793"
  STLOS_ESCROW_CONTRACT_ADDRESS = "0xB679ab23726d7EaF1b3b807b018A27362E7B85F8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
